name: Buid and Deploy Container Image

on:
    workflow_call:
      inputs:
        context-path:
          required: true
          type: string
        tag-name:
          required: true
          type: string
        registry_name: 
          required: true
          type: string
      secrets:
        REGISTRY_USERNAME:
          required: true
          description: The user name associated with the container registry
        REGISTRY_PASSWORD:
          required: true
          description: The password or acces token associated with the container registry

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry_name }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push tag
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context-path }}
          push: true
          tags: ${{ inputs.tag-name }}