name: Buid and Deploy Container Image

on:
    workflow_call:
      inputs:
        context-path:
          required: true
          type: string
        tag-name:
          required: true
          type: string
        registry-name: 
          required: true
          type: string
        build-args:
          required: false
          type: string
      secrets:
        REGISTRY-USERNAME:
          required: true
          description: The user name associated with the container registry
        REGISTRY-PASSWORD:
          required: true
          description: The password or acces token associated with the container registry

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry-name }}
          username: ${{ secrets.REGISTRY-USERNAME }}
          password: ${{ secrets.REGISTRY-PASSWORD }}

      - name: Build and push tag
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context-path }}
          push: true
          tags: |
           ${{ inputs.tag-name }}
          build-args: | 
            ${{ inputs.build-args }}