name: Build and Deploy Docker Image

on:
    workflow_call:
      inputs:
        context-path:
          required: true
          type: string
        tag-name:
          required: true
          type: string
      secrets:
        GHCR_PAT:
          required: true
        REPO_OWNER:
          required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.REPO_OWNER }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context-path }}
          push: true
          tags: ${{ inputs.tag-name }}